config/routes.rb
Rails.application.routes.draw do

  get '/top' => 'homes#top'
  root to: 'homes#top'

  # ユーザー用
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }

  # 管理者用
  devise_for :admin, skip: [:registrations] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :homes, only: [:top]
    resources :users, only: [:index, :show, :edit, :destroy, :update] do
      member do
        get :userphotos
        get :useralbums
      end
    end
    resources :photo_images, only: [:index, :show, :destroy] do
      resources :photo_comments, only: [:destroy]
    end
    resources :albums, only: [:index, :show, :destroy]

    resources :album_photo_images, only: [:index, :show, :destroy] do
      resources :album_photo_comments, only: [:destroy]
    end
  end

  scope module: :public do
    resources :users, only:[:mypage, :show, :index, :favo_photoall, :edit, :update] do
      member do
        get :photo_images
        get :favorites
        get :album_favorites
        get :album_photo_images_favorites
        get :useralbums
        get :userphotos
        get :favo_photoall
        get :favo_albumall
        get :favo_albumphotoall
      end
      collection do
        get '/mypage' => 'users#mypage', as: 'mypage'
        get 'mypage/edit' => 'users#edit', as: 'edit'
        get '/mypage' => 'users#update', as: 'update'
        get :confirm
        patch 'withdraw' => 'users#withdraw', as: 'withdraw'
      end
    end

    resources :photo_images, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
      resource :favorites, only: [:create, :destroy]
      resources :photo_comments, only: [:create, :destroy] do
        resource :goods, only: [:create, :destroy]
      end
      member do
        get :photo_images
      end
      collection do
        get 'search'
      end
    end
    resources :albums, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
      collection do
        get 'search'
        get 'releases'
      end
      resource :album_favorites, only: [:create, :destroy]
      member do
        get :album
      end
    end
    resources :album_photo_images, only: [:index, :show, :edit, :destroy, :update] do
      resource :album_photo_image_favorites, only: [:create, :destroy]
      resources :album_photo_comments, only: [:create, :destroy] do
        resource :album_photo_goods, only: [:create, :destroy]
      end
      member do
        get :album_photo_images
      end
    end
    resources :notifications, only: [:index, :destroy] do
      collection do
        post 'destroy_all' => 'notifications#destroy_all'
      end
    end
  end
end

app/models/photo_image.rb
class PhotoImage < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :favorites, dependent: :destroy
  has_many :photo_comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end


  def self.search(year = nil, month = nil, day = nil)
    if month != nil
      if month.length == 1
        month = "0" + month
      end
    end
    if day != nil
      if day.length == 1
        day = "0" + day
      end
    end
    if year.present? && month.present? && day.present?
      date = year + month + day
      PhotoImage.where(created_at: date.in_time_zone.all_day)
    elsif year.present? && month.present?
      date = year + month + "01"
      PhotoImage.where(created_at: date.in_time_zone.all_month)
    elsif year.present?
      date = year + "01" + "01"
      PhotoImage.where(created_at: date.in_time_zone.all_year)
    else
      PhotoImage.all
    end
  end




  def create_notification_comment!(visiter, photo_comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = PhotoComment.where(photo_image_id: id).where.not(user_id: visiter.id).select(:user_id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(visiter.id, photo_comment_id, temp_id['user_id'])
    end
  	# まだ誰もコメントしていない場合は、投稿者に通知を送る
  	save_notification_comment!(visiter.id, photo_comment_id, user_id) if temp_ids.blank?
  end

	def save_notification_comment!(visiter_id, photo_comment_id, visited_id)
    notification = Notification.new(
      photo_image_id: id,
      photo_comment_id: photo_comment_id,
      visited_id: visited_id,
      visiter_id: visiter_id,
      action: 'photo_comment'
    )
    if notification.visiter_id == notification.visited_id
      notification.checked = true
    end
    notification.save! if notification.valid?
  end

   validates :image, presence: true


  # enum status: { public: 0, private: 1 }, _prefix: true

end

app/controllers/admin/photo_images_controller.rb
class Admin::PhotoImagesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @photo_images = PhotoImage.order('id DESC').page(params[:page])
    @photo_image_count = PhotoImage.where(params[:photo_image_id]).count
  end

  def show
    @photo_image = PhotoImage.find(params[:id])
    @user = @photo_image.user
  end

  def destroy
    @photo_image = PhotoImage.find(params[:id])
    @photo_image.destroy
    redirect_to admin_photo_images_path
  end



private

  def photo_image_params
    params.require(:photo_image).permit(:user_id, :photo_title, :photo_caption)
  end

end

app/helpers/admin/photo_images_helper.rb
module Admin::PhotoImagesHelper
end

app/views/admin/photo_images/_index.html.erb
<% photo_images.each do |photo_image| %>
<div class="col-3 px-2">
  <div class="photo-all">
    <%= link_to admin_photo_image_path(photo_image.id)do %>
      <%= image_tag photo_image.get_image(500, 500), class: 'album-image-cover' %>
    <% end %>
    <div class="flex">
      <div class="comments">
        <i class="fa-solid fa-comment" style="color: #60a39b;"></i>
        <%= link_to "#{photo_image.photo_comments.count} ", photo_image_path(photo_image.id), :style=>"color: gray;" %>
      </div>
      <div class="edit-delete">
          <%= link_to admin_photo_image_path(photo_image.id), method: :delete, class: "link" do %>
            <i class="fa-solid fa-trash-can"></i>
          <% end %>
      </div>
    </div>
    <div class="box">
      <%= photo_image.created_at.strftime('%Y/%m/%d') %>
    </div>
  </div>
</div>
<% end %>
<div class="container">
  <%= paginate @photo_images %>
</div>

app/views/admin/photo_images/index.html.erb
<div class="container">
  <br>
  <h3 class="box">PHOTO ALL <span><%= @photo_image_count %>件</span></h3>
</div>

<div class="container">
  <div class="row row no-gutters">
    <%= render 'admin/photo_images/index', photo_images: @photo_images %>
  </div>
</div>

app/views/admin/photo_images/show.html.erb
<div class="container">
  <div class="photo">
    <div class="row">
      <div class="col"></div>
      <div class="col-10">
        <div class="image">
          <% if @photo_image.image.attached? %>
            <%= image_tag @photo_image.image, class: 'img-fluid' %>
          <% end %>
        </div>
      </div>
      <div class="col"></div>
    </div>
    <div class="row">
      <div class="col"></div>
      <div class="col-10">
        <div class="flex">
          <div class="comments">
            <i class="fa-solid fa-comment" style="color: #60a39b;"></i> <%= @photo_image.photo_comments.count %>
          </div>
          <div class="edit-delete">
            <%= link_to admin_photo_image_path(@photo_image.id), method: :delete, class: "link" do %>
              <i class="fa-solid fa-trash-can"></i>
            <% end %>
            <br>
          </div>
        </div>
      </div>
      <div class="col"></div>
    </div>
    <div class="row">
      <div class="col"></div>
      <div class="col-10">
        <div class="title">
          <% if @photo_image.photo_title.present? %>
            <%= @photo_image.photo_title %>
          <% else %>
            <div class="blank"></div>
          <% end %>
        </div>
        <div class="cap">
          <% if @photo_image.photo_caption.present? %>
            <%= @photo_image.photo_caption %>
          <% else %>
            <div class="blank"></div>
          <% end %>
        </div>
        <div class="flex">
          <div class="name">
            <%= image_tag @photo_image.user.get_profile_image(20,20) %>
            <%= @photo_image.user.name %>
          </div>
          <div class="time">
            <%= @photo_image.created_at.strftime('%Y/%m/%d %H:%M') %>
          </div>
        </div>
      </div>
      <div class="col"></div>
    </div>
    <div class="row">
      <div class="col"></div>
      <div class="col-10">
        <div class="comment-good">
          <div class="text-comment">comment</div>
          <% @photo_image.photo_comments.each do |photo_comment| %>
          <div class="row">
            <div class="col-2">
              <div class="box">
                <%= image_tag photo_comment.user.get_profile_image(20,20) %><%= photo_comment.user.name %>
              </div>
            </div>
            <div class="col-5">
              <div class="box">
                <%= photo_comment.comment %>
              </div>
            </div>
            <div class="col-3">
              <div class="box">
                <%= photo_comment.created_at.strftime('%Y/%m/%d %H:%M') %>
              </div>
            </div>
            <div class="col-1">
              <div class="box">
                <%= link_to admin_photo_image_photo_comment_path(photo_comment.photo_image, photo_comment), method: :delete, class: "link" do %>
                  <i class="fa-solid fa-trash-can"></i>
                <% end %>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
      <div class="col"></div>
    </div>
  </div>
</div>
<div class="container">
  <div class="col-10">
    <%= link_to "PHOTO ALLへ戻る", admin_photo_images_path, class: "btn btn-outline-lightgreen" %>
  </div>
</div>