config/routes.rb
Rails.application.routes.draw do

  get '/top' => 'homes#top'
  root to: 'homes#top'

  # ユーザー用
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }

  # 管理者用
  devise_for :admin, skip: [:registrations] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :homes, only: [:top]
    resources :users, only: [:index, :show, :edit, :destroy, :update] do
      member do
        get :userphotos
        get :useralbums
      end
    end
    resources :photo_images, only: [:index, :show, :destroy] do
      resources :photo_comments, only: [:destroy]
    end
    resources :albums, only: [:index, :show, :destroy]

    resources :album_photo_images, only: [:index, :show, :destroy] do
      resources :album_photo_comments, only: [:destroy]
    end
  end

  scope module: :public do
    resources :users, only:[:mypage, :show, :index, :favo_photoall, :edit, :update] do
      member do
        get :photo_images
        get :favorites
        get :album_favorites
        get :album_photo_images_favorites
        get :useralbums
        get :userphotos
        get :favo_photoall
        get :favo_albumall
        get :favo_albumphotoall
      end
      collection do
        get '/mypage' => 'users#mypage', as: 'mypage'
        get 'mypage/edit' => 'users#edit', as: 'edit'
        get '/mypage' => 'users#update', as: 'update'
        get :confirm
        patch 'withdraw' => 'users#withdraw', as: 'withdraw'
      end
    end

    resources :photo_images, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
      resource :favorites, only: [:create, :destroy]
      resources :photo_comments, only: [:create, :destroy] do
        resource :goods, only: [:create, :destroy]
      end
      member do
        get :photo_images
      end
      collection do
        get 'search'
      end
    end
    resources :albums, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
      collection do
        get 'search'
        get 'releases'
      end
      resource :album_favorites, only: [:create, :destroy]
      member do
        get :album
      end
    end
    resources :album_photo_images, only: [:index, :show, :edit, :destroy, :update] do
      resource :album_photo_image_favorites, only: [:create, :destroy]
      resources :album_photo_comments, only: [:create, :destroy] do
        resource :album_photo_goods, only: [:create, :destroy]
      end
      member do
        get :album_photo_images
      end
    end
    resources :notifications, only: [:index, :destroy] do
      collection do
        post 'destroy_all' => 'notifications#destroy_all'
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_one_attached :profile_image

  has_many :albums

  has_many :album_releases, dependent: :destroy
  has_many :released_albums, through: :album_releases, source: :album

  has_many :photo_images, dependent: :destroy

  has_many :favorites, dependent: :destroy
  # favoriteをとおして、フォトイメージを結ぶ
  has_many :favorited_photo_images, through: :favorites, source: :photo_image
  #  has_many_attached :album
  has_many :album_favorites, dependent: :destroy
  has_many :favorited_albums, through: :album_favorites, source: :album

  has_many :album_photo_image_favorites, dependent: :destroy
  has_many :favorited_album_photo_images, through: :album_photo_image_favorites, source: :album_photo_image

  has_many :photo_comments, dependent: :destroy
  has_many :album_photo_comments, dependent: :destroy

  has_many :goods, dependent: :destroy
  has_many :album_photo_goods, dependent: :destroy

  has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy

  devise :database_authenticatable, :registerable, :timeoutable

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/猫のシルエット.png')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end





  def favorited_by?(photo_image_id)
    favorites.where(photo_image_id: photo_image_id).exists?
  end

  def album_favorited_by?(album_id)
    album_favorites.where(album_id: album_id).exists?
  end

  def album_photo_image_favorited_by?(album_photo_image_id)
    album_photo_image_favorites.where(album_photo_image_id: album_photo_image_id).exists?
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_user_path(@user.id)
  end

  def userphotos
    @user = User.find(params[:id])
    @photo_images = @user.photo_images.order('id DESC').page(params[:page])
    @photo_images_count = @user.photo_images.count
  end

  def useralbums
    @user = User.find(params[:id])
    @albums = @user.albums.order('id DESC').page(params[:page]).per(12)
    @albums_count = @user.albums.count
  end


  private

  def user_params
    params.require(:user).permit(:email, :name, :birthdate, :introduction, :is_active, :is_deleted, :user_id)

  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-1"></div>
    <div class="col-11">
      <div class="box">
        <h2 class="text-left">
          <strong><%= @user.name %></strong>さんの会員情報編集<br><br>
        </h2>
      </div>
    </div>
  </div>
  <%= form_with model: @user, url: admin_user_path(@user.id), method: :patch do |f| %>
  <div class="row">
    <div class="col-1"></div>
    <div class="col-3">
      <div class="box">
        <div class="field">
          <i class="fa-brands fa-ideal"></i>
          <%= f.label :id %>
        </div>
      </div>
    </div>
    <div class="col-8">
      <div class="box">
        <%= f.text_field :id, autofocus: true, autocomplete: "id" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-1"></div>
    <div class="col-3">
      <div class="box">
        <div class="field">
          <i class="fa-solid fa-user"></i>
          <%= f.label :name %>
        </div>
      </div>
    </div>
    <div class="col-8">
      <div class="box">
        <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-1"></div>
    <div class="col-3">
      <div class="box">
        <div class="field">
          <i class="fa-solid fa-image-portrait"></i>
          <%= f.label :profile_image %>
        </div>
      </div>
    </div>
    <div class="col-8">
      <div class="box">
        <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-1"></div>
    <div class="col-3">
      <div class="box">
        <div class="field">
          <i class="fa-solid fa-cake-candles"></i>
          <%= f.label :birthdate %>
        </div>
      </div>
    </div>
    <div class="col-8">
      <div class="box">
        <%= f.date_field :birthdate %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-1"></div>
    <div class="col-3">
      <div class="box">
        <div class="field">
          <i class="fa-solid fa-circle-info"></i>
          <%= f.label :introduction %>
        </div>
      </div>
    </div>
    <div class="col-8">
      <div class="box">
        <%= f.text_field :introduction %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-1"></div>
    <div class="col-3">
      <div class="box">
        <div class="field">
          <i class="fa-solid fa-envelope"></i>
          <%= f.label :email %>
        </div>
      </div>
    </div>
    <div class="col-8">
      <div class="box">
        <%= f.text_field :email %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-1"></div>
    <div class="col-3">
      <div class="box">
        <div class="field">
          <i class="fa-solid fa-circle-question"></i>
          <%= f.label :会員ステータス %>
        </div>
      </div>
    </div>
    <div class="col-8">
      <div class="box">
        <%= f.radio_button "is_active", "true", id: "radio1" %>
        　<label for="radio1">有効</label>
        <%= f.radio_button "is_active", "false", id: "radio2" %>
          <label for="radio2">退会</label>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-1"></div>
    <div class="col-3"></div>
    <div class="col-8">
      <div class="box">
        <%= f.submit "UPDATE", class: "btn btn-outline-lightgreen w-25" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-1"></div>
    <div class="col-3"></div>
    <div class="col-8">
      <div class="box">
        <%= link_to "back", admin_user_path(@user), class: "btn btn-outline-lightgreen w-25" %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <br>
  <h3 class="box">User All</h3>
</div>
<div class="container">
  <div class="row">
    <div class="col-1"></div>
    <div class="col-1">
      <div class="box">
        <i class="fa-brands fa-ideal"></i> id
      </div>
    </div>
    <div class="col-3">
      <div class="box">
        <i class="fa-solid fa-user"></i> name
      </div>
    </div>
    <div class="col-4">
      <div class="box">
        <i class="fa-solid fa-cake-candles"></i> email
      </div>
    </div>
    <div class="col-3">
      <div class="box">
        <p>会員ステータス</p>
      </div>
    </div>
  </div>
  <% @users.each do |user| %>
  <div class="row">
    <div class="col-1"></div>
    <div class="col-1">
      <div class="box">
        　<%= user.id %>
      </div>
    </div>
    <div class="col-3">
      <div class="box">
        　<%= image_tag user.get_profile_image(20,20), class: "rounded-circle" %>
        <%= link_to admin_user_path(user.id) , class: "link" do %>
          <%= user.name %>
        <% end %>
      </div>
    </div>
    <div class="col-4">
      <div class="box">
        　<%= user.email %>
      </div>
    </div>
    <div class="col-3">
      <div class="box">
        <% if user.is_active %>
          <p class="font-weight-bold text-success">　有効</p>
        <% else %>
          <p>　退会</p>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-8">
      <div class="box">
        <br>
        <h3 class="bold box">Information</h3>
        <br>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-2">
      <div class='profileimage'>
        <%= image_tag @user.get_profile_image(120,120), class: "rounded-circle" %>
      </div>
    </div>
    <div class="col-6 d-flex align-items-center">
      <h3 class="bold box"><%= @user.name %></h3>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-1"></div>
    <div class="col-2">
      <div class="box">
        <i class="fa-brands fa-ideal"></i> id
      </div>
    </div>
    <div class="col-8">
      <div class="box">
        <%= @user.id %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-1"></div>
    <div class="col-2">
      <div class="box">
        <i class="fa-solid fa-user"></i> name
      </div>
    </div>
    <div class="col-8">
      <div class="box">
        <%= @user.name %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-1"></div>
    <div class="col-2">
      <div class="box">
        <i class="fa-solid fa-cake-candles"></i> birthday
      </div>
    </div>
    <div class="col-8">
      <div class="box">
        <%= @user.birthdate %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-1"></div>
    <div class="col-2">
      <div class="box">
        <i class="fa-solid fa-circle-info"></i> introduction
      </div>
    </div>
    <div class="col-8">
      <div class="box">
        <%= @user.introduction %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-1"></div>
    <div class="col-2">
      <div class="box">
        <i class="fa-solid fa-envelope"></i> email
      </div>
    </div>
    <div class="col-8">
      <div class="box">
        <%= @user.email %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-1"></div>
    <div class="col-2">
      <div class="box"></div>
    </div>
    <div class="col-8">
      <div class="box">
        <i class="fa-solid fa-image fa-1"></i>
        <%= link_to userphotos_admin_user_path(@user.id), class: "link2" do %>
          <span style="color: gray;", onMouseOver="this.style.color='#cc7eb1'", onMouseOut="this.style.color='gray'", class="link">
             PHOTO
          </span>
        <% end %>
        <span style="color: gray;"><<%= @user.photo_images.count %>photos></span>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-1"></div>
    <div class="col-2">
      <div class="box"></div>
    </div>
    <div class="col-8">
      <div class="box">
        <i class="fa-solid fa-images fa-1"></i>
        <%= link_to useralbums_admin_user_path(@user.id), class: "link2" do  %>
          <span style="color: gray;", onMouseOver="this.style.color='#cc7eb1'", onMouseOut="this.style.color='gray'", class="link">
             ALBUM
          </span>
        <% end %>
        <span style="color: gray;"><<%= @user.albums.count %>albums></span>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-1"></div>
    <div class="col-2">
      <div class="box">
        <p>会員ステータス</p>
      </div>
    </div>
    <div class="col-8">
      <div class="box">
        <% if @user.is_active %>
          <p class="font-weight-bold text-success">有効</p>
        <% else %>
          <p>退会</p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-1"></div>
    <div class="col-2">
      <div class="box"></div>
    </div>
    <div class="col-8">
      <%= link_to "edit", edit_admin_user_path(@user), class: "btn btn-outline-lightgreen" %>
    </div>
  </div>
  <div class="row">
    <div class="col-1"></div>
    <div class="col-2">
      <div class="box"></div>
    </div>
    <div class="col-8">
      <%= link_to "USER一覧へ戻る", admin_users_path, class: "btn btn-outline-lightgreen" %>
    </div>
  </div>
</div>

app/views/admin/users/useralbums.html.erb
<div class="container">
  <br>
  <h3 class="box"><%= @user.name %>'s ALBUM<span class="count-font">　<<%= @albums_count %>albums></span></h3>
</div>
<div class="container">
  <div class="row">
    <%= render 'admin/albums/index', albums: @user.albums %>
  </div>
</div>
<div class="container">
  <%= link_to "#{@user.name}'s pageへ戻る", admin_user_path(@user.id), class: "btn btn-outline-lightgreen" %>
</div>

app/views/admin/users/userphotos.html.erb
<div class="container">
  <br>
  <h3 class="box"><%= @user.name %>'s Photo<span class="count-font">　<<%= @photo_images_count %>photos></span></h3>
</div>

<div class="container">
  <div class="row">
      <%= render 'admin/photo_images/index', photo_images: @photo_images %>
  </div>
</div>

<div class="container">
  <%= link_to "#{@user.name}'s pageへ戻る", admin_user_path(@user.id), class: "btn btn-outline-lightgreen" %>
</div>