config/routes.rb
Rails.application.routes.draw do

  get '/top' => 'homes#top'
  root to: 'homes#top'

  # ユーザー用
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }

  # 管理者用
  devise_for :admin, skip: [:registrations] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :homes, only: [:top]
    resources :users, only: [:index, :show, :edit, :destroy, :update] do
      member do
        get :userphotos
        get :useralbums
      end
    end
    resources :photo_images, only: [:index, :show, :destroy] do
      resources :photo_comments, only: [:destroy]
    end
    resources :albums, only: [:index, :show, :destroy]

    resources :album_photo_images, only: [:index, :show, :destroy] do
      resources :album_photo_comments, only: [:destroy]
    end
  end

  scope module: :public do
    resources :users, only:[:mypage, :show, :index, :favo_photoall, :edit, :update] do
      member do
        get :photo_images
        get :favorites
        get :album_favorites
        get :album_photo_images_favorites
        get :useralbums
        get :userphotos
        get :favo_photoall
        get :favo_albumall
        get :favo_albumphotoall
      end
      collection do
        get '/mypage' => 'users#mypage', as: 'mypage'
        get 'mypage/edit' => 'users#edit', as: 'edit'
        get '/mypage' => 'users#update', as: 'update'
        get :confirm
        patch 'withdraw' => 'users#withdraw', as: 'withdraw'
      end
    end

    resources :photo_images, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
      resource :favorites, only: [:create, :destroy]
      resources :photo_comments, only: [:create, :destroy] do
        resource :goods, only: [:create, :destroy]
      end
      member do
        get :photo_images
      end
      collection do
        get 'search'
      end
    end
    resources :albums, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
      collection do
        get 'search'
        get 'releases'
      end
      resource :album_favorites, only: [:create, :destroy]
      member do
        get :album
      end
    end
    resources :album_photo_images, only: [:index, :show, :edit, :destroy, :update] do
      resource :album_photo_image_favorites, only: [:create, :destroy]
      resources :album_photo_comments, only: [:create, :destroy] do
        resource :album_photo_goods, only: [:create, :destroy]
      end
      member do
        get :album_photo_images
      end
    end
    resources :notifications, only: [:index, :destroy] do
      collection do
        post 'destroy_all' => 'notifications#destroy_all'
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
      <title>Recollections</title>
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
      <script src="https://kit.fontawesome.com/7e258a15bb.js" crossorigin="anonymous"></script>
  </head>
  <body>
    <header class="header fixed-top">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <span>
            <a class="navbar-brand" href="/" >recollections</a>
            <% if current_user %>
              <%= link_to new_photo_image_path, class: "link" do %>
                <i class="fa-solid fa-image fa-2x"></i>
              <% end %>
              <%= link_to new_album_path, class: "link" do %>
                <i class="fa-solid fa-images fa-2x"></i>
              <% end %>
            <% elsif current_admin %>
              <span class="admin">ADMIN</span>
            <% else %>
            <% end %>
          </span>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
          aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <% if current_user %>
                <% if unchecked_notifications.any? %>
                  <i class="fa fa-circle" style="color: gold;"></i>
                <% end %>
                <li>
                  <%= link_to "NOTICE", notifications_path, class: "btn btn-outline-turquoise w-90" %>
                </li>
                <li>
                  <%= link_to "MYPAGE", mypage_users_path, class: "btn btn-outline-turquoise w-90" %>
                </li>
                <li>
                  <%= link_to "PHOTO", photo_images_path, class: "btn btn-outline-turquoise w-90" %>
                </li>
                <li>
                  <%= link_to "ALBUM", albums_path, class: "btn btn-outline-turquoise w-90" %>
                </li>
                <li>
                  <%= link_to "USER", users_path, class: "btn btn-outline-turquoise w-90" %>
                </li>
                <li>
                  <%= link_to "LOGOUT", destroy_user_session_path, method: :delete, class: "btn btn-outline-turquoise w-90" %>
                </li>
              <% elsif current_admin %>
                <li>
                  <%= link_to "PHOTO", admin_photo_images_path, class: "btn btn-outline-yellow w-90" %>
                </li>
                <li>
                  <%= link_to "ALBUM", admin_albums_path, class: "btn btn-outline-yellow w-90" %>
                </li>
                <li>
                  <%= link_to "USER", admin_users_path, class: "btn btn-outline-yellow w-90" %>
                </li>
                <li>
                  <%= link_to "LOGOUT", destroy_admin_session_path, method: :delete, class: "btn btn-outline-yellow w-90" %>
                </li>
              <% else %>
                <%= link_to "新規登録", new_user_registration_path, class: "btn btn-outline-turquoise" %>
                <%= link_to "LOGIN", user_session_path, class: "btn btn-outline-turquoise" %>
              <% end %>
            </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer class="footer-top">
      <div class="container">
        <div class="box">
          m.a©︎
        </div>
      </div>
    </footer>
  </body>
</html>